version: "3.7"
services:  
    # postgres used by airflow
    postgres:
        image: postgres:9.6
        networks:
            - default_net
        volumes: 
            # Create Test database on Postgresql
            - ./docker-airflow/pg-init-scripts:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"

    # airflow LocalExecutor
    airflow-webserver:
        image: paclflst/docker-airflow-spark:1.10.7_3.1.2
        restart: always
        networks:
            - default_net
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW_CONN_STR_SPARK_DEFAULT=spark://spark:7077
            # - LOG_FILE=/usr/local/spark/resources/outfile.log
            - LOG_FILE=/usr/local/spark/logs/outfile.log
            - LOG_LEVEL=DEBUG
        volumes:
            - ../dags:/usr/local/airflow/dags #DAG folder
            - ../spark/app:/usr/local/spark/app #Spark Scripts (Must be the same path in airflow and Spark Cluster)
            - ../spark/resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
            - ../spark/app/utils:/usr/local/airflow/dags/utils # utils folder
            - ../logs:/usr/local/spark/logs
        ports:
            - "8282:8282"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    # Spark with 3 workers
    spark:
        image: bitnami/spark:3.1.2
        user: root # Run container as root container: https://docs.bitnami.com/tutorials/work-with-non-root-containers/
        hostname: spark
        networks:
            - default_net
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ../spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
            - ../spark/resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
            - ../logs:/usr/local/spark/logs
        ports:
            - "8181:8080"
            - "7077:7077"

    spark-worker-1:
        image: bitnami/spark:3.1.2
        user: root
        networks:
            - default_net
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1100m
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ../spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
            - ../spark/resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
            - ../logs:/usr/local/spark/logs
            # - ../utils:/usr/local/spark/app/modules/utils # utils folder

    web-api:
        # image: flask_docker:latest
        build: ../web_api
        restart: always
        networks:
            - default_net
        depends_on:
            - postgres
        environment:
            - EXECUTOR=Local
            - LOG_LEVEL=DEBUG
            - LOG_FILE=/usr/local/spark/logs/outfile.log
        volumes:
            - ../web_api:/app 
            - ../spark/app/utils:/app/utils # utils folder
            - ../logs:/usr/local/spark/logs
        ports:
            - "5000:5000"
        command: app.py

networks:
    default_net:

    # spark-worker-2:
    #     image: bitnami/spark:3.1.2
    #     user: root
    #     networks:
    #         - default_net
    #     environment:
    #         - SPARK_MODE=worker
    #         - SPARK_MASTER_URL=spark://spark:7077
    #         - SPARK_WORKER_MEMORY=1100m
    #         - SPARK_WORKER_CORES=1
    #         - SPARK_RPC_AUTHENTICATION_ENABLED=no
    #         - SPARK_RPC_ENCRYPTION_ENABLED=no
    #         - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    #         - SPARK_SSL_ENABLED=no
    #     volumes:
    #         - ../spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
    #         - ../spark/resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)

    # spark-worker-3:
    #     image: bitnami/spark:3.1.2
    #     user: root
    #     networks:
    #         - default_net
    #     environment:
    #         - SPARK_MODE=worker
    #         - SPARK_MASTER_URL=spark://spark:7077
    #         - SPARK_WORKER_MEMORY=500m
    #         - SPARK_WORKER_CORES=1
    #         - SPARK_RPC_AUTHENTICATION_ENABLED=no
    #         - SPARK_RPC_ENCRYPTION_ENABLED=no
    #         - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    #         - SPARK_SSL_ENABLED=no
    #     volumes:
    #         - ../spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
    #         - ../spark/resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)

    #Jupyter notebook
    # jupyter-spark:
    #     image: jupyter/pyspark-notebook:spark-3.1.2
    #     networks:
    #         - default_net
    #     ports:
    #       - "8888:8888"
    #       - "4040-4080:4040-4080"
    #     volumes:
    #       - ../notebooks:/home/jovyan/work/notebooks/
    #       - ../spark/resources/data:/home/jovyan/work/data/
    #       - ../spark/resources/jars:/home/jovyan/work/jars/